export const SET_WATCH_ACTIVATION_CODE = 'SET_WATCH_ACTIVATION_CODE';
export const REMOVE_WATCH_ACTIVATION_CODE = 'REMOVE_WATCH_ACTIVATION_CODE';

export const PAIR_CONNECT_RESET = 'PAIR_CONNECT_RESET';
export const PAIR_CONNECT = 'PAIR_CONNECT';
export const PAIR_CONNECT_SUCCESS = 'PAIR_CONNECT_SUCCESS';
export const PAIR_CONNECT_GENERAL_FAILURE = 'PAIR_CONNECT_GENERAL_FAILURE';
export const PAIR_CONNECT_BLUETOOTH_FAILURE = 'PAIR_CONNECT_BLUETOOTH_FAILURE';
export const PAIR_CONNECT_LOCATION_FAILURE = 'PAIR_CONNECT_LOCATION_FAILURE';
