export const actions = {
  FIRMWARE_VERSION_SET_WATCH_VERSION : 'FIRMWARE_VERSION_SET_WATCH_VERSION',
  FIRMWARE_VERSION_SET_NEW_VERSION : 'FIRMWARE_VERSION_SET_NEW_VERSION',
  FIRMWARE_VERSION_SET_NEW_VERSION_AVAILABLE : 'FIRMWARE_VERSION_SET_NEW_VERSION_AVAILABLE',
  FIRMWARE_VERSION_SET_UPDATE_VERSION : 'FIRMWARE_VERSION_SET_UPDATE_VERSION',
  FIRMWARE_VERSION_RESET_UPDATE_VERSION : 'FIRMWARE_VERSION_RESET_UPDATE_VERSION',
  FIRMWARE_STORE_META : 'FIRMWARE_STORE_META',
};