export const SET_WATCH_CONNECTION = 'SET_WATCH_CONNECTION';
export const SET_WATCH_WORN_STATUS = 'SET_WATCH_WORN_STATUS';

export const SET_HEALTH_VALUES = 'SET_HEALTH_VALUES';

export const SET_WATCH_WORN_POPUP_VISIBILITY =
  'SET_WATCH_WORN_POPUP_VISIBILITY';
export const SET_WATCH_CONNECTION_POPUP_VISIBILITY =
  'SET_WATCH_CONNECTION_POPUP_VISIBILITY';
export const SET_WATCH_SYNC_VISIBILITY = 'SET_WATCH_SYNC_VISIBILITY';

export const SHOULD_REFRESH_SCREEN = 'SHOULD_REFRESH_SCREEN';

//Watch Related Actions
export const OFFLINE_SYNC_START = 'OFFLINE_SYNC_START';
export const OFFLINE_SYNC_COMPLETED = 'OFFLINE_SYNC_COMPLETED';
export const OFFLINE_SYNC_PROGRESS = 'OFFLINE_SYNC_PROGRESS';

export const SET_WATCH_BATTERY_STATUS = 'SET_WATCH_BATTERY_STATUS';
export const SET_WATCH_CHARGER_STATUS = 'SET_WATCH_CHARGER_STATUS';
export const SET_WATCH_WRIST_STATUS = 'SET_WATCH_WRIST_STATUS';

export const SET_WATCH_CHARGER_VISIBILITY = 'SET_WATCH_CHARGER_VISIBILITY';
