export const WEIGHT_UNIT = {
  MKS: 'MKS',
  FPS: 'FPS',
};

export const GLUCOSE_UNIT = {
  MGDL: 'mg/dL',
  MMOL: 'mmol/L',
};

export const WEATHER_UNIT = {
  IMPERIAL: 1, // Fahrenheit / Mile
  METRIC: 0, // Celsius / Kilometer
}

export const PAIRING_STATE = {
  PAIR_NOT_STARTED: 0,
  PAIR_REQUESTED: 1,
  PAIR_SUCCESSFUL: 2,
  PAIR_CONNECT_STARTED: 3,
  PAIR_CONNECT_FAILED: 4,
  PAIR_CONNECT_SUCCESS: 5,
};

export const PAIRING_STATE_FAILURE_CODE = {
  GENERAL_FAILURE: 1,
  CONNECTION_NOT_AVAILABLE: 2,
  BLUETOOTH_NOT_AVAILABLE: 3,
  LOCATION_NOT_AVAILABLE: 4,
  BATTERY_LOW: 5,
};

export const WATCH_CONNECTION_STATE = {
  NOT_CONNECTED: 0,
  CONNECTED: 1,
  SYNCING: 2,
};

export const WATCH_WORN_STATE = {
  NOT_WORN: 0,
  WORN: 1,
};

export const INSTANT_MEASURE_STATE = {
  RESET: 0,
  FAILED: 1,
  SUCCESS: 2,
  ONGOING: 3,
};

export const INSTANT_MEASURE_FAILURE_CODE = {
  GENERAL_FAILURE: 1,
  CONNECTION_NOT_AVAILABLE: 2,
  BLUETOOTH_NOT_AVAILABLE: 3,
  LOCATION_NOT_AVAILABLE: 4,
  BATTERY_LOW: 5,
};

export const INSTANT_CALIBRATE_STATE = {
  RESET: 0,
  FAILED: 1,
  SUCCESS: 2,
  ONGOING: 3,
  STEP_ONE: 4,
  STEP_TWO: 5,
  STEP_THREE: 6,
  INITIAL: 7,
};

export const INSTANT_CALIBRATE_FAILURE_CODE = {
  GENERAL_FAILURE: 1,
  CONNECTION_NOT_AVAILABLE: 2,
  BLUETOOTH_NOT_AVAILABLE: 3,
  LOCATION_NOT_AVAILABLE: 4,
  BATTERY_LOW: 5,
};

export const USER_REGISTRATION_STATE = {
  HAS_NOT_FILLED_TC: 1,
  HAS_NOT_FILLED_PERSONAL_INFO: 2,
  HAS_PASSTHROUGH: 3,
};

export const UI_TOAST_STATE = {
  SHOW_TOAST: 1,
  HIDE_TOAST: 2,
};

export const CALIBRATE_RANGES = {
  BLOOD_GLUCOSE_LOW: 0,
  BLOOD_GLUCOSE_HIGH: 1000,
  HEART_RATE_LOW: 40,
  HEART_RATE_HIGH: 180,
  BLOOD_PRESSURE_SYS_LOW: 70,
  BLOOD_PRESSURE_SYS_HIGH: 220,
  BLOOD_PRESSURE_DIA_LOW: 40,
  BLOOD_PRESSURE_DIA_HIGH: 130,
  RESPIRATION_RATE_LOW: 10,
  RESPIRATION_RATE_HIGH: 30,
  OXYGEN_SATURATION_LOW: 80,
  OXYGEN_SATURATION_HIGH: 100,
};

export const MEALS_STATE = {
  RESET_MEALS: 0,
  REFRESH_MEAL: 1,
};

export const OFFLINE_SYNC_STATE = {
  SYNC_NOT_STARTED: 0,
  SYNC_START: 1,
  SYNC_COMPLETE: 2,
  SYNC_PROGRESS: 3,
};

export const WATCH_BATTERY_STATE = {
  NORMAL: 0,
  LOW: 1,
};

export const WATCH_CHARGER_STATE = {
  CONNECTED: 0,
  NOT_CONNECTED: 1,
};

export const WATCH_WRIST_STATE = {
  ON_WRIST: 0,
  NOT_ON_WRIST: 1,
};

export const AUTO_MEASURE_STATE = {
  STARTED: 0,
  NOT_STARTED: 1,
};
