export const APP_SYNC_SUCCESS = {
  APPSYNC_ACKNOWLEDGE: 298,
  APP_SYNC_COMPLETED: 299,
};

export const APP_SYNC_ERROR = {
  INVALID_USER: '004',
  INVALID_MSN: '011',
  OTHER_PROC_RUNNING: '013',
  APPSYNC_ERROR: '211',
};
