export const CONNECT_SUCCESS = {
  WATCH_CONNECTED: 199,
  CONNECT_ACKNOWLEDGE: 198,
  DISCOVERING_SERVICES: 197,
};

export const CONNECT_IGNORE = {};

export const CONNECT_ERROR = {
  DISCONNECT: '002',
  NOT_CONNECTED: '003',
  INVALID_USER: '004',
  INVALID_USER_SESSION: '005',
  DATA_PARSE_ERR: '006',
  OP_TIMEOUT: '008',
  DB_OP_ERR: '009',
  INVALID_MSN: '011',
  INVALID_AUTH: '101',
  WATCH_UNAVAILABLE: '102',
  UNMATCH_AUTH_ID: '103',
  WATCH_REJECT_AUTH: '104',
  BLE_NO_PERMISSION: '105',
  LOCATION_NO_PERMISSION: '106',
  WATCH_REJECT_BOND: '107',
  INDICATE_SBSCRIPTION_FAIL: '108',
  GATT_DISCOVER_FAIL: '109',
  GATT_WRITE_FAIL: '110',
  GATT_READ_FAIL: '111',
  UNABLE_START_SCANNING: '112',
  UNABLE_START_SERVICE_DISCOVERY: '113',
  INVALID_DEVICE: '114',
  CALIBRATION_FAILED: '115',
  INSTANT_MEASURE_FAILED: '116',
};
