export const OFFLINE_DATA_READ = {
  OFFLINE_VITAL_COMMAND_FAILED: '304',
  OFFLINE_VITAL_READ_COMPLETE: '305',
  OFFLINE_VITAL_READ_START: '306',
  OFFLINE_VITAL_READ_IN_PROGRESS: '307',
};

export const WATCH_BATTERY_CONS = {
  WATCH_BATTERY_LOW: '022',
  WATCH_BATTERY_NORMAL: '023',
  WATCH_CHARGER_CONNECTED: '024',
  WATCH_CHARGER_DISCONNECTED: '025',
  WATCH_NOT_ON_WRIST: '026',
  WATCH_ON_WRIST: '027',
  WATCH_SHUTDOWN_IN_PROGRESS: '030',
};

export const FIRMWARE_UPDATE = {
  FIRMWARE_UPDATE_START: '501',
  FIRMWARE_UPDATE_ERROR_FILE_PARSE: '502',
  FIRMWARE_UPDATE_ERROR_FILE_READ: '503',
  FIRMWARE_UPDATE_ERROR_CONNECTION: '504',
  FIRMWARE_UPDATE_ERROR_COMMUNICATION: '505',
  FIRMWARE_UPDATE_ERROR_CRC: '506',
  FIRMWARE_UPDATE_ERROR_INSTALLATION: '507',
  FIRMWARE_UPDATE_INVALID_FILE: '508',
  FIRMWARE_UPDATE_COMPLETE: '509',
};
