export const APP_SYNC_GENERAL_FAILURE = 'APP_SYNC_GENERAL_FAILURE';
export const APP_SYNC_UNIT_FAILURE = 'APP_SYNC_UNIT_FAILURE';

export const START_APP_SYNC = 'START_APP_SYNC';

export const TOGGLE_CGM_DEBUG = 'TOGGLE_CGM_DEBUG';
export const TOGGLE_DEBUG_LOG = 'TOGGLE_DEBUG_LOG';

export const APP_SYNC_COMPLETED = 'APP_SYNC_COMPLETED';

export const RESET_APP_SYNC = 'RESET_APP_SYNC';
