export const WATCH_CALIBRATE_IN_PROGRESS = 'WATCH_CALIBRATE_IN_PROGRESS';
export const WATCH_CALIBRATE_RESET = 'WATCH_CALIBRATE_RESET';
export const WATCH_CALIBRATE_SUCCESS = 'WATCH_CALIBRATE_SUCCESS';
export const WATCH_CALIBRATE_GENERAL_ERROR = 'WATCH_CALIBRATE_GENERAL_ERROR';
export const WATCH_CALIBRATE_BATTERY_LOW = 'WATCH_CALIBRATE_BATTERY_LOW';
export const WATCH_CALIBRATE_CONNECTION_BLUETOOTH_ERROR = 'WATCH_CALIBRATE_CONNECTION_BLUETOOTH_ERROR';
export const WATCH_CALIBRATE_SHOW_INITIAL_FORM = 'WATCH_CALIBRATE_SHOW_INITIAL_FORM';

export const CGM_ON = "CGM_ON";
export const CGM_OFF = "CGM_OFF";

export const AUTO_CALIBRATE_ON = "AUTO_CALIBRATE_ON";
export const AUTO_CALIBRATE_OFF = "AUTO_CALIBRATE_ON";


export const STEP_ONE = 'STEP_ONE';
export const STEP_TWO = 'STEP_TWO';
export const STEP_THREE = 'STEP_THREE';