export const SET_DEVICE_ACTIVATION_CODE = 'SET_DEVICE_ACTIVATION_CODE';
export const REMOVE_DEVICE_ACTIVATION_CODE = 'REMOVE_DEVICE_ACTIVATION_CODE';

export const PAIR_CONNECT_RESET = 'PAIR_CONNECT_RESET';
export const PAIR_CONNECT = 'PAIR_CONNECT';
export const PAIR_CONNECT_SUCCESS = 'PAIR_CONNECT_SUCCESS';
export const PAIR_CONNECT_GENERAL_FAILURE = 'PAIR_CONNECT_GENERAL_FAILURE';
