export const SET_HIDE_ALERT_BADGE = 'SET_HIDE_ALERT_BADGE';
export const SET_SHOW_ALERT_BADGE = 'SET_SHOW_ALERT_BADGE';
export const SET_ALERTS_AS_OPENED = 'SET_ALERTS_AS_OPENED';
export const SET_ALERTS_AS_DELETED = 'SET_ALERTS_AS_DELETED';
export const SET_ALERTS_AS_EDITED = 'SET_ALERTS_AS_EDITED';
