export const WATCH_MEASURE_IN_PROGRESS = 'WATCH_MEASURE_IN_PROGRESS';
export const WATCH_MEASURE_RESET = 'WATCH_MEASURE_RESET';
export const WATCH_MEASURE_SUCCESS = 'WATCH_MEASURE_SUCCESS';
export const WATCH_MEASURE_GENERAL_ERROR = 'WATCH_MEASURE_GENERAL_ERROR';
export const WATCH_MEASURE_BATTERY_LOW = 'WATCH_MEASURE_BATTERY_LOW';
export const WATCH_MEASURE_CONNECTION_BLUETOOTH_ERROR =
  'WATCH_MEASURE_CONNECTION_BLUETOOTH_ERROR';

export const AUTO_MEASURE_IN_PROGRESS = 'AUTO_MEASURE_IN_PROGRESS';
